 /******************************************************************************
 *
 * Module: ULTRASONIC
 *
 * File Name: ultrasonic.c
 *
 * Description: Source file for the ultrasonic sensor
 *
 * Author: Mahmoud Abdalla
 *
 *******************************************************************************/
#include "ultrasonic.h"
#include "icu.h"
#include "gpio.h"
#include "std_types.h"
#include <util/delay.h>
#include <avr/io.h>

Icu_ConfigType config = {F_CPU_8,RISING}; /* set the Configuration of the ICU*/
uint8 g_edgeCount = 0; /* number of edges detected by ICU */
uint32 g_timeHigh = 0; /* time high for distance */

/*
 * Description : Function to initialize the ULTRASONIC sensor
 * 	1. Initialize the ICU driver as required.
 * 	2. Setup the ICU call back function.
 * 	3. Setup the direction for the trigger pin as output pin through the GPIO driver.
 */
void Ultrasonic_init(){
	Icu_init(&config);    /* Initialize the ICU driver as required. */
	Icu_setCallBack(Ultrasonic_edgeProcessing); /* set call back function of icu */
	/* Setup the direction for the trigger pin as output pin through the GPIO driver.  */
	GPIO_setupPinDirection(ULTRASONIC_TRIGGER_PORT, ULTRASONIC_TRIGGER_PIN, PIN_OUTPUT);
}

/*
 * Description: Send the Trigger pulse to the ultrasonic.
 */
void Ultrasonic_Trigger(void){
	/* Send the Trigger pulse to the ultrasonic = 10us   */
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT, ULTRASONIC_TRIGGER_PIN, LOGIC_HIGH);
	_delay_us(10); /* delay to send logic high for 10 microseconds */
	/* Make the trigger logic low   */
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT, ULTRASONIC_TRIGGER_PIN, LOGIC_LOW);
}


/*
 * Description: Send the trigger pulse by using Ultrasonic_Trigger function.
 *              Start the measurements by the ICU from this moment.
 */
uint16 Ultrasonic_readDistance(void){
	/* Initialize distance to 0 to measure it */
	uint16 distance = 0;
	/* Send the trigger pulse by using Ultrasonic_Trigger function. */
	Ultrasonic_Trigger();
	/* Start the measurements by the ICU from this moment. */
	distance = g_timeHigh / 58.8;
	return distance;
}


/*
 * Description: This is the call back function called by the ICU driver.
                This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void){
	/* increasing edges so if edge == 1 timer counter will be 0 and take the value of counter when
	 * failing edge = 2
	 */
	g_edgeCount++;
	if(g_edgeCount == 1){
		/* clear timer value to equal 0 */
		/* set edge as falling */
		Icu_clearTimerValue();
		Icu_setEdgeDetectionType(FALLING);
		g_timeHigh = 0;
	}
	else if(g_edgeCount == 2){
		/*
		 * and take value of ICR1
		 */
		g_timeHigh = Icu_getInputCaptureValue();
		Icu_DeInit();  /* Deinitializing of ICU */
		g_edgeCount = 0;
		Icu_setEdgeDetectionType(RISING);
	}
}
